Refactor hydrotest
geoadmin/suite-bdms pull request #1012
Opened 2024-02-07 08:59 UTC by tschumpr

Resolves #689 
Working on #972

2024-02-07 12:10 UTC, danjov requested changes

2024-02-07 12:10 UTC, danjov commented on src/client/cypress/e2e/helpers/formHelpers.js
> +    // cy.wait("@codelist_GET");
REQ: Auskommentierten Code löschen

2024-02-07 12:10 UTC, danjov commented on src/client/cypress/e2e/helpers/formHelpers.js
> +    // cy.wait("@codelist_GET");
REQ: Auskommentierten Code löschen

2024-02-07 12:20 UTC, danjov approved these changes

2024-02-07 16:28 UTC, MiraGeowerkstatt commented on src/client/src/api/fetchApiV2.js
> -export const useHydrotests = boreholeId =>
Q: Ich habe es nicht mehr im Kopf, brauchen wir die hydrotest queries nirgends anders, sodass hier die Mutations gestrichen werden können?

2024-02-07 16:28 UTC, MiraGeowerkstatt commented on src/client/src/commons/form/borehole/hydrogeology/hydrotestInput.js
> -  const convertDateToIsoString = dateTime =>
Q: warum fliegt die Funktion raus?

2024-02-12 07:41 UTC, MiraGeowerkstatt approved these changes

2024-02-12 07:51 UTC, merged