Use new api for codelist updates
geoadmin/suite-bdms pull request #103
Opened 2022-09-29 14:01 UTC by MiraGeowerkstatt

2022-09-29 14:22 UTC, danjov requested changes

2022-09-29 14:22 UTC, danjov commented on .github/workflows/ci.yml
>          run: docker-compose up -d minio db api-legacy api
PP: Man könnte diesen Step aufteilen und hier nur die Datenbank starten und erst nach den erfolgreichen .NET Tests die APIs mit MinIO hochfahren.

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +    public BdmsContext Context { get; }
REQ: Zu einem `private readonly`-Feld umwandeln, da wir von ausserhalb vermutlich nicht auf den Context des Controllers zugreifen müssen.

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +    /// <param name = "schema">The schema of the codeLists to get.</param>
PP: Unnötige Whitespaces in XML-Dokumentation entfernen
```suggestion
    /// <param name="schema">The schema of the codelists to get.</param>
```

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +    /// Asynchronously gets the <see cref="Codelist"/>s, optionally filtered by <paramref name= "schema"/>.
PP: Unnötige Whitespaces in XML-Dokumentation entfernen
```suggestion
    /// Asynchronously gets the <see cref="Codelist"/>s, optionally filtered by <paramref name="schema"/>.
```

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +    /// <param name ="codelist"> The <see cref="Codelist"/> to update.</param>
PP: Unnötige Whitespaces in XML-Dokumentation entfernen
```suggestion
    /// <param name="codelist">The <see cref="Codelist"/> to update.</param>
```

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +        // update properties if presernt in codelist parameter
REQ: Typos fixen und Kommentare immer mit Grossbuchstaben beginnen
```suggestion
        // Update properties if present in codelist parameter
```

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +        foreach (PropertyInfo propertyInfo in codelist.GetType().GetProperties())
Q: Werden nicht immer alle Properties vom Client geschickt?

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +    private async Task<IActionResult> SaveChangesAsync(Func<IActionResult> successResult)
PP: Das diese Methode nur einen Aufrufer hat, kann sie oben _inlined_ werden.

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +        return await SaveChangesAsync(() => new OkObjectResult(codeListToUpdate)).ConfigureAwait(false);
PP: Erfolgreiche Rückgaben können vereinfacht ausgedrückt werden mit `Ok(..)`:
```suggestion
        return await SaveChangesAsync(() => Ok(codeListToUpdate)).ConfigureAwait(false);
```

2022-09-29 14:22 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +            return Problem(errorMessage, statusCode: StatusCodes.Status400BadRequest);
REQ: ILogger in den Controller injecten und die jetzige Meldung loggen. An den Client sollten nicht alle Fehlerdetails zurückgeschickt werden, sondern nur das Wichtigste wie z.B. `return Problem("Error while updating the codelist entry.", statusCode: StatusCodes.Status400BadRequest);`

2022-09-29 14:22 UTC, danjov commented on src/api/Models/Codelist.cs
> +    public bool? Default { get; set; }
REQ: Abstände zwischen den Properties einführen.

2022-09-29 14:22 UTC, danjov commented on src/api/Models/Codelist.cs
> +namespace BDMS.Models;
REQ: Leere Zeile nach dem Namespace einführen.

2022-09-29 14:22 UTC, danjov commented on tests/CodeListControllerTest.cs
> +        httpClient = new HttpClient();
REQ: Der `httpClient` wird nirgends verwendet und kann gelöscht werden.

2022-09-29 14:22 UTC, danjov commented on tests/CodeListControllerTest.cs
> +    public async Task EditWithoutCodelistRetursBadRequest()
PP: Typo fixen
```suggestion
    public async Task EditWithoutCodelistReturnsBadRequest()
```

2022-09-29 14:22 UTC, danjov commented on tests/ContextFactory.cs
> +namespace BDMS;
REQ: Leere Zeile nach dem Namespace.

2022-09-30 08:06 UTC, MiraGeowerkstatt commented on src/api/Controllers/CodeListController.cs
> +        foreach (PropertyInfo propertyInfo in codelist.GetType().GetProperties())
Ja stimmt jetzt mit der Umstellung am Client können wir immer alles überschreiben .

2022-09-30 08:16 UTC, danjov commented on src/api/Controllers/CodeListController.cs
> +        foreach (PropertyInfo propertyInfo in codelist.GetType().GetProperties())
Gerne 👍🏻

2022-09-30 08:54 UTC, danjov approved these changes

2022-09-30 11:14 UTC, danjov approved these changes

2022-09-30 11:46 UTC, merged