Split join table for layer codelists
geoadmin/suite-bdms pull request #1051
Opened 2024-02-21 16:53 UTC by MiraGeowerkstatt

Resolves #256

2024-02-22 07:41 UTC, MiraGeowerkstatt commented on src/api/Models/LayerColorCode.cs
> +public class LayerColorCode : ILayerCode
Ja ist doof, wir hatten es länger in der gesamten Applikation als "color" amerikanisch, aber Michael hat sich jetzt "colour" als Schemanamen gewünscht.

2024-02-22 07:41 UTC, MiraGeowerkstatt commented on src/api/Migrations/20240220143043_SplitCodelistJoinTables.cs
> +        migrationBuilder.DropTable(
Ich wusste das mir ein wichtiges Detail entfallen war 😵‍💫

2024-02-22 09:00 UTC, danjov commented on src/api/Controllers/UploadController.cs
> +    internal List<int> ParseIds(string ids)
REQ: Kurze XML-Dokumentation für die Methode hinzufügen

2024-02-22 09:01 UTC, danjov commented on src/api/Controllers/UploadController.cs
> +            .Select(s =>
PP: `Split()` ebenfalls auf die nächste Zeile nehmen, so gewinnt der gesamte Ausdruck an Struktur und die String-Operationen sind schön untereinander.

2024-02-22 09:03 UTC, danjov commented on src/api/Controllers/UploadController.cs
>          return splittedList.Where(s => !string.IsNullOrEmpty(s)).Select(int.Parse).ToList() ?? new List<int>();
PP: Das ganze liesse sich in einem Statement zusammenfassen und gleich zurückgeben.

2024-02-22 09:08 UTC, danjov commented on src/api/Migrations/20240220143043_SplitCodelistJoinTables.cs
> +                id_cli_fk = table.Column<int>(type: "integer", nullable: false),
REQ: Die Namensgebung der Spalten folgt dem Legacy-Code und nicht der neuen Namensgebung, hier wäre es `layer_id` anstatt `id_lay_fk` und `codelist_id` (oder `color_id`?) anstatt `id_cli_fk`. Die FKs müssen entsprechend auch angepasst werden. Das betrifft alle Zwischentabellen-Migrations.

2024-02-22 09:09 UTC, danjov commented on src/api/Migrations/20240220143043_SplitCodelistJoinTables.cs
> +    protected override void Down(MigrationBuilder migrationBuilder)
FYI: Die `Down`-Methode kannst du bei Bedarf weglassen, da wir dieses Feature nicht einsetzen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerColorCode.cs
> +    public Codelist Codelist { get; set; }
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerDebrisCode.cs
>      [Column("id_lay_fk")]
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerGrainAngularityCode.cs
> +    [Column("id_lay_fk")]
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerGrainShapeCode.cs
> +    public int LayerId { get; set; }
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerOrganicComponentCode.cs
> +    [Column("id_lay_fk")]
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:40 UTC, danjov commented on src/api/Models/LayerUscs3Code.cs
> +    public int LayerId { get; set; }
REQ: XML-Dokumentation aus Interface mit `inheritdoc` übernehmen.

2024-02-22 09:45 UTC, danjov commented on tests/Controllers/BoreholeControllerTest.cs
> +    private IQueryable<Borehole> IncludeBoreholeData(IQueryable<Borehole> query)
PP: Alternativvorschlag für den Namen: `GetBoreholeWithIncludes`

2024-02-22 09:46 UTC, danjov commented on tests/Controllers/BoreholeControllerTest.cs
REQ: Leere Zeile löschen

2024-02-22 09:48 UTC, danjov commented on tests/Controllers/UploadControllerTest.cs
> +            .ToList().Find(b => b.OriginalName == "Seth Patel");
PP: Das Laden der Daten mit allen Includes in Methode auslagern und wiederverwenden im Test.

2024-02-22 10:24 UTC, MiraGeowerkstatt commented on src/api/BdmsContextExtensions.cs
> +                        combinations.Remove(combination);
Es konnte sonst sein, dass eine Kombination mehrfach eingefügt wurde und es Probleme mit den unique constraints gab. Den if Block brauchts zwar glaube ich nicht (mehr). Ich teste es 👍

2024-02-22 10:35 UTC, MiraGeowerkstatt commented on src/api/Controllers/BoreholeController.cs
> +                if (layer.LayerUscs3Codes != null) ResetLayerIds(layer.LayerUscs3Codes);
Ja hatte ich auch zuerst, aber dann bekomme ich einen [CS8604](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8604)#possible-null-assigned-to-a-nonnullable-reference) - Possible null reference argument for parameter.
Einfach mit ! (null-forgiving)  übergeben?

2024-02-22 10:45 UTC, MiraGeowerkstatt commented on src/api/Controllers/LayerController.cs
> +        await UpdateLayerCodesAsync(existingLayer.LayerColorCodes ?? new List<LayerColorCode>(), entity.ColorCodelistIds ?? new List<int>(), existingLayer.Id).ConfigureAwait(false);
Gleiches Problem mit CS8604 wie oben :(

2024-02-22 10:54 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +                if (layer.LayerUscs3Codes != null) ResetLayerIds(layer.LayerUscs3Codes);
Ja, dafür kann der null-forgiving Operator eingesetzt werden.

2024-02-26 08:01 UTC, MiraGeowerkstatt commented on src/api/Migrations/20240220143043_SplitCodelistJoinTables.cs
> +    protected override void Down(MigrationBuilder migrationBuilder)
Ja bei selbstgeschriebenen SQL Migrationen habe ich das jeweils weggelassen, bei den generierten ist es bisher immer drin geblieben.

2024-02-26 11:15 UTC, danjov requested changes

2024-02-26 11:15 UTC, danjov commented on src/api/Models/ILayerCodeExtensions.cs
>  public static class ILayerCodeExtensions
REQ: Umbenennen, da es kein Interface ist
```suggestion
public static class LayerCodeExtensions
```

2024-02-26 11:19 UTC, danjov submitted a review, later dismissed

2024-02-26 12:10 UTC, danjov approved these changes

2024-02-26 14:29 UTC, merged