Add borehole sections
geoadmin/suite-bdms pull request #1184
Opened 2024-04-04 10:23 UTC by patrickackermann

See https://github.com/geoadmin/suite-bdms/issues/1102

2024-04-08 14:57 UTC, danjov requested changes
Ansonsten lgtm

2024-04-08 14:57 UTC, danjov commented on src/api/Migrations/20240404074334_AddSectionsTables.cs
> +                drilling_method_id_cli = table.Column<int>(type: "integer", nullable: true),
REQ: Den Zusatz `_cli` weglassen, da wir das bei neuen Tabellen nicht mehr anfügen (siehe vorherige Migrationen). Gilt für alle Felder, die auf `codelist` verweisen.

2024-04-09 08:23 UTC, MiraGeowerkstatt requested changes

2024-04-09 08:23 UTC, MiraGeowerkstatt commented on src/client/public/locale/it/common.json
> +  "drilling_mud_subtype": "Sottotipo di fango di perforazion",
REQ: Ich glaube da fehlt ein e am Ende.

2024-04-09 08:23 UTC, MiraGeowerkstatt commented on src/client/src/commons/form/borehole/borehole/sectionInput.jsx
> +      <DevTool control={formMethods.control} placement="top-left" />
Q: Soll das im finalen Code drin bleiben? (Machst du mal ein Project coffe zu dem Tool? würde mich interessieren !).

2024-04-09 08:25 UTC, danjov submitted a review, later dismissed

2024-04-09 08:31 UTC, patrickackermann commented on src/client/src/commons/form/borehole/borehole/sectionInput.jsx
> +      <DevTool control={formMethods.control} placement="top-left" />
Das sind die DevTools von react-hook-forms, ich nehme an, dass sie im prod build nicht sichtbar sind ähnlich wie die dev-tools von react-query.

2024-04-09 08:32 UTC, MiraGeowerkstatt commented on src/client/src/commons/form/borehole/borehole/sectionInput.jsx
> +      <DevTool control={formMethods.control} placement="top-left" />
💡

2024-04-09 11:49 UTC, MiraGeowerkstatt approved these changes

2024-04-09 11:56 UTC, merged