Copy borehole
geoadmin/suite-bdms pull request #131
Opened 2022-10-24 09:39 UTC by patrickackermann

Fixes https://github.com/geoadmin/suite-bdms/issues/25

2022-10-24 10:28 UTC, danjov requested changes
REQ: Changelog nachführen

2022-10-24 10:28 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +            .ConfigureAwait(false);
PP: Da wir kein Tracking auf `workgroup` oder `user` benötigen, können diese auch mit `.AsNoTracking()` von der DB geholt werden.

2022-10-24 10:28 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        }
REQ: Das Holen und Prüfen der Benutzerrechte ganz an den Anfang schieben. So werden das `borehole` und die `workgroup` erst geladen, wenn man genügend Rechte hat.

2022-10-24 10:28 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        // Set ids of copied entities to zero
PP: Im Kommentar kurz beschreiben, dass durch das Setzen der ID auf 0 neue Einträge in der DB erstellt werden.

2022-10-24 10:28 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        borehole.Workflows.Add(new Workflow() { Borehole = borehole, Role = Role.Editor, User = user });
PP: Die Klammern kann man sich beim Objektinitialisierungs-Syntax sparen
```suggestion
        borehole.Workflows.Add(new Workflow { Borehole = borehole, Role = Role.Editor, User = user });
```

2022-10-24 10:28 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        borehole.CreatedBy = user;
Q: Muss das `Created`-Datum auch noch gesetzt werden und müssen die Informationen in `UpdatedBy` bzw. `Updated` gelöscht werden?

2022-10-24 10:28 UTC, danjov commented on src/client/cypress/e2e/editor/copyBorehole.cy.js
> +    cy.wait("@workflow_edit_list");
Q: Wäre es nicht klarer, die API Interceptions direkt hier zu haben anstatt im `testHelper` solange sie auch nur von hier gebraucht werden?

2022-10-24 10:28 UTC, danjov commented on src/client/cypress/e2e/editor/copyBorehole.cy.js
> +    cy.contains("a", "Delete").click();
PP/Q: Kann hier kurz geprüft werden, ob die Kopie anhand vom Titel erstellt wurde und angezeigt wird?

2022-10-24 10:28 UTC, danjov commented on tests/BoreholeControllerTest.cs
> +
PP: Weitern Testfall mit unbekanntem Benutzer hinzufügen.

2022-10-24 10:33 UTC, MiraGeowerkstatt commented on src/client/cypress/e2e/editor/copyBorehole.cy.js
> +    cy.wait("@workflow_edit_list");
PP: Noch irgendwie asserten, dass die kopierten Werte dargestellt werden.

2022-10-24 10:33 UTC, MiraGeowerkstatt commented on tests/BoreholeControllerTest.cs
> +        Assert.AreNotSame(originalBorehole.Stratigraphies.First().Layers.First(), copiedBorehole.Stratigraphies.First().Layers.First());
Q:  Wird hier einfach  asserted, dass die kopierten Stratigraphien eine neue Id bekommen? Wird noch irgendwo festgestellt ob die Attribute etc. richtig kopiert werden?

2022-10-24 11:40 UTC, flenny commented on src/api/Controllers/BoreholeController.cs
> +        if (borehole == null || workgroup == null || user == null)
REQ: Bei `user==null` auch `Unauthorized()` zurückgeben.

2022-10-24 12:48 UTC, patrickackermann commented on src/api/Controllers/BoreholeController.cs
> +        }
Bei einer nicht vorhandenen `workgroup` wird dann auch `Unauthorized` zurückgegeben, da auf der user auf der inexistenten workgroup keine Editor Permission hat.

2022-10-24 12:54 UTC, patrickackermann commented on src/client/cypress/e2e/editor/copyBorehole.cy.js
> +    cy.wait("@workflow_edit_list");
Der `Workflow/edit` endpoint wird im Zusammenhang mit dem Workflow mit verschiedenen Actions genutzt. Daher hätte ich diesen Intersept im `testHelper` gelassen auch wenn er im Moment nur hier verwendet wird.

`borehole_copy` entferne ich aus `testHelper`.

2022-10-24 12:54 UTC, danjov commented on src/api/Controllers/BoreholeController.cs
> +        }
Ja, man müsste die Prüfung trennen: z.B. wie von @flenny vorgeschlagen zuerst den User auf `null` prüfen und ggf. gleich `Unauthorized` zurückgeben. Danach kann man die `workgroup` laden und die jetzige Rechteprüfung durchführen und zum Schluss das `borehole` laden inkl. Prüfung auf `null`.

2022-10-25 06:17 UTC, danjov submitted a review, later dismissed

2022-10-25 06:25 UTC, flenny commented on src/api/Controllers/BoreholeController.cs
> +        }
Q/PP: Ich bin grad ein bisschen unsicher, aber dieser Anwendungsfall wird höchstwahrscheinlich nicht vorkommen, da die entsprechende [Middleware](https://github.com/geoadmin/suite-bdms/blob/main/src/api/Authentication/BasicAuthenticationHandler.cs#L54) vorher dicht macht. Ist es möglich, dass du via Test-Framework hier gelandet bist (weil dort die ganzen Middlewares möglicherweise nicht miteinbezogen werden 🤷🏼)? Von mir aus könnte der Abschnitt weg.

2022-10-25 06:25 UTC, flenny approved these changes

2022-10-25 06:55 UTC, patrickackermann commented on src/api/Controllers/BoreholeController.cs
> +        }
Ja, wenn ich beim Testen den User nicht setze lande ich hier.

2022-10-25 06:55 UTC, patrickackermann commented on tests/BoreholeControllerTest.cs
> +        Assert.AreNotSame(originalBorehole.Stratigraphies.First().Layers.First(), copiedBorehole.Stratigraphies.First().Layers.First());
Ja, es wird getestet, dass das neue Borehole nicht die gleichen Stratigraphien referenziert. Ich denke es ist klarer, wenn ich direkt schaue, dass die Ids nicht gleich sind und das ist auch robuster, falls _originalBorehole_ und _copiedBorehole_ ausversehen mit verschiedenen contexts geladen wurden.

Ich habe noch ein Assert für ein Property hinzugefügt, damit der Test sicher failt, falls einfach ein leerer Layer daherkommt.

2022-10-25 06:57 UTC, flenny approved these changes

2022-10-25 08:46 UTC, merged