Use new api for layer display
geoadmin/suite-bdms pull request #296
Opened 2023-01-20 10:16 UTC by MiraGeowerkstatt

Vorbereitung für Welltops & #277

2023-01-20 16:12 UTC, danjov requested changes

2023-01-20 16:12 UTC, danjov commented on src/client/cypress/e2e/admin/userAdministration.cy.js
> +    loginAndResetBoreholes();
REQ: `loginAndResetBoreholes()` und `interceptApiCalls()` sollen in einen [Root-Level-Hook](https://github.com/mochajs/old-mochajs-site/blob/master/index.md#root-level-hooks) bzw. [Support-File](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file) ausgelagert werden, so sparen wir uns den Aufruf in jedem einzelnen Test.

2023-01-23 07:44 UTC, MiraGeowerkstatt commented on src/api/BdmsContext.cs
> +        modelBuilder.Entity<Layer>().HasOne(l => l.InstrumentCasing).WithMany().HasForeignKey(l => l.InstrumentCasingId);
Ja, es wundert mich auch dass es das braucht. Bevor ich die Codelist collection (für die m:n Beziehung) auf dem Layer hatte, existierten alle diese Properties  schon und wurden korrekt verknüpft. Irgendwie scheint EF dann aber durcheinander zu kommen, seit es die Collection gibt und ich musste es explizit machen.

2023-01-23 10:00 UTC, danjov approved these changes

2023-01-23 10:17 UTC, merged