Remove descriptions from lithology
geoadmin/suite-bdms pull request #460
Opened 2023-02-23 09:23 UTC by MiraGeowerkstatt

Resolves #430

2023-02-23 09:43 UTC, danjov submitted a review, later dismissed

2023-02-23 09:46 UTC, patrickackermann submitted a review, later dismissed

2023-02-23 10:13 UTC, danjov requested changes
REQ: Die Felder müssen auch beim PDF-Export entfernt werrden.

2023-02-24 07:29 UTC, danjov approved these changes

2023-02-24 08:17 UTC, merged