Replace csv import coordinates related columns by location_x and location_y
geoadmin/suite-bdms pull request #546
Opened 2023-03-29 14:39 UTC by Lehats

Resolves #542

2023-03-31 13:57 UTC, patrickackermann requested changes

2023-03-31 13:57 UTC, patrickackermann commented on src/api/Controllers/UploadController.cs
> +                await coordinateService.MigrateCoordinatesOfBorehole(borehole, false).ConfigureAwait(false);
PP: Für boolean Argumente _named Arguments_ verwenden, Hier z.B.
```suggestion
                await coordinateService.MigrateCoordinatesOfBorehole(borehole, onlyMissing: false).ConfigureAwait(false);
```

PP: Ich hätte diesen Aufruf in `UpdateBoreholeLocation` gelassen damit das Setzen von Location und Municipality etc. nicht so verteilt ist.

2023-03-31 13:57 UTC, patrickackermann commented on tests/CoordinateServiceTest.cs
> +        Assert.AreEqual(0, CoordinateService.GetDecimalPlaces(100));
REQ: Test mit grösserer Zahl im Bereich der erwarteten Koordinaten.

2023-03-31 13:57 UTC, patrickackermann commented on tests/CoordinateServiceTest.cs
> +        // Only calculate misssing values.
REQ: Fix typo

```suggestion
        // Only calculate missing values.
```

2023-04-03 07:47 UTC, patrickackermann requested changes

2023-04-03 07:47 UTC, patrickackermann commented on src/api/Controllers/CoordinateController.cs
> +                var coordinatesBeforeMigration = $"{borehole.LocationX}{borehole.LocationY}{borehole.LocationXLV03}{borehole.LocationYLV03}";
REQ: `coordinatesBeforeMigration` wird nicht verwendet, bitte entfernen.

2023-04-03 07:50 UTC, danjov requested changes

2023-04-03 07:50 UTC, danjov commented on CHANGELOG.md
> +- Replace csv import coordinates related columns by _`location_x`_ and _`location_y`_.
PP: Die technischen Spaltennamen entweder kursiv oder als Code formatiert darstellen, jedoch nicht beides zusammen.

2023-04-03 07:50 UTC, danjov commented on src/api/Controllers/CoordinateController.cs
> +                // Select the coordinates before migration for later comparisation.
Q: Wo wird `coordinatesBeforeMigration` verwendet?

REQ: Typo fixen
```suggestion
                // Select the coordinates before migration for later comparison.
```

2023-04-03 07:50 UTC, danjov commented on src/api/Controllers/UploadController.cs
> +            Map(b => b.LocationX).Convert(args => { return args.Row.GetField<double?>("location_x") >= 2_000_000 ? args.Row.GetField<double?>("location_x") : null; });
PP: Ohne die geschweiften Klammern lässt sich das einfacher ausdrücken:
```suggestion
            Map(b => b.LocationX).Convert(args => args.Row.GetField<double?>("location_x") >= 2_000_000 ? args.Row.GetField<double?>("location_x") : null);
```

2023-04-03 07:50 UTC, danjov commented on src/api/Controllers/UploadController.cs
> +            Map(b => b.LocationY).Convert(args => { return args.Row.GetField<double?>("location_y") >= 1_000_000 ? args.Row.GetField<double?>("location_y") : null; });
Q: Was geschieht hier, wenn im CSV-File die beiden Koordinaten-Spalten fehlen? Gibt es einen Test dazu?

2023-04-03 07:50 UTC, danjov commented on tests/CoordinateControllerTest.cs
> +        var loggerCoordinateServiceMock = new Mock<ILogger<CoordinateService>>();
Q: Wurde hier absichtlich das `MockBehavior` nicht konfiguriert?

2023-04-03 07:50 UTC, danjov commented on tests/CoordinateServiceTest.cs
> +    public async Task NotMigrateCoordinatesOfLV03BoreholeWithMissingSourceCoordinates()
PP: Der Methodenname klingt ein wenig holprig. Alternativvorschlag:
```suggestion
    public async Task DoesNotMigrateCoordinatesOfLV03BoreholeWithMissingSourceCoordinates()
```

2023-04-03 07:50 UTC, danjov commented on tests/CoordinateServiceTest.cs
> +    public async Task NotMigrateCoordinatesOfLV95BoreholeWithAllCoordinatesSet()
PP: Der Methodenname klingt ein wenig holprig. Alternativvorschlag:
```suggestion
    public async Task DoesNotMigrateCoordinatesOfLV95BoreholeWithAllCoordinatesSet()
```

2023-04-03 07:50 UTC, danjov commented on tests/UploadControllerTest.cs
> +        var borehole = context.Boreholes.First(b => b.OriginalName != null && b.OriginalName.Contains("LV95 - All coordinates set"));
PP: Hier können wir ein bisschen strenger sein und das Borehole mit `Single` holen, da wir immer exakt ein Borehole für diese Bedingung erwarten.

2023-04-03 12:19 UTC, Lehats commented on src/api/Controllers/UploadController.cs
> +            Map(b => b.LocationY).Convert(args => { return args.Row.GetField<double?>("location_y") >= 1_000_000 ? args.Row.GetField<double?>("location_y") : null; });
Habe ein Test erstelt.

2023-04-03 12:20 UTC, Lehats commented on src/api/Controllers/CoordinateController.cs
> +                // Select the coordinates before migration for later comparisation.
War überflüssig.

2023-04-03 12:28 UTC, patrickackermann approved these changes

2023-04-03 12:28 UTC, danjov approved these changes

2023-04-03 12:28 UTC, danjov commented on tests/BDMS.Test.csproj
> +    <None Update="TestData\lv03_coordinates_provided_testdata.csv">
REQ/PP: Einfachheitshalber hätte ich den Ordner lower-case `testdata` genannt. So muss man sich keine Gedanken über die korrekte Schreibweise des Ordners machen :).

2023-04-04 05:03 UTC, merged