Changed all db attributes of type date to timestamp with time zone
geoadmin/suite-bdms pull request #548
Opened 2023-03-31 11:30 UTC by Lehats

Resolves #250

2023-03-31 14:12 UTC, patrickackermann requested changes

2023-03-31 14:12 UTC, patrickackermann commented on src/api/Migrations/20230331101139_ConvertDateOnlyToDateTime.cs
> +where table_name like 'completness');
Q: Hat es da wirklich noch ein Schreibfehler: `completness` -> `completeness`

2023-04-03 06:34 UTC, Lehats commented on src/api/Migrations/20230331101139_ConvertDateOnlyToDateTime.cs
> +where table_name like 'completness');
Gut gesehen, aber ja, dieser Schreibfehler ist so vorhanden.

2023-04-03 07:34 UTC, patrickackermann approved these changes

2023-04-03 09:36 UTC, danjov approved these changes
LGTM. Soll jedoch vorerst noch nicht gemerged werden.

2023-04-04 14:41 UTC, danjov approved these changes

2023-04-05 07:12 UTC, merged