Add endpoints to dotnet API for managing borehole files
geoadmin/suite-bdms pull request #609
Opened 2023-04-25 11:04 UTC by Lehats

Working on #598

2023-04-25 12:50 UTC, danjov requested changes

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +        if (boreholeId == 0) return BadRequest("No BoreholeId provided.");
PP: Exakten Parameter-Namen in Fehlermeldung ausgeben
```suggestion
        if (boreholeId == 0) return BadRequest("No boreholeId provided.");
```

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            logger.Log(LogLevel.Error, ex, "An error occurred while downloading the file.");
REQ: `ILogger.LogError` verwenden.

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +        if (boreholeFileId == 0) return BadRequest("No BoreholeFileId provided.");
PP: Exakten Parameter-Namen in Fehlermeldung ausgeben.

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            if (boreholeFile?.File != null)
Q: Sollte hier nicht auf `file` geprüft werden?

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            var file = boreholeFile.File;
REQ: Hier könnte eine `NullReferenceException` auftreten, falls `boreholeFile == null` ist. Umschreiben zu `var file = boreholeFile?.File;`, dann kann man zwei Zeilen weiter unten gleich auf `file` prüfen.

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +                context.Files.Remove(file);
Q: Gibt es keine `RemoveAsync()`-Methode?

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            logger.Log(LogLevel.Error, ex, "An error occurred while detaching the file.");
REQ: `ILogger.LogError` verwenden.

2023-04-25 12:50 UTC, danjov commented on src/api/Controllers/UploadController.cs
> +                    foreach (var boreholeImport in boreholeImports)
PP: Es wäre sinnvoll, wenn wir hier nur die Boreholes mit Attachments behandeln. Beispiel:
```csharp
var boreholeImportsWithAttachments = boreholeImports.Where(x => x.Attachmants.Any()).ToList();
foreach (var boreholeImport in boreholeImportsWithAttachments)
{}
```

2023-04-25 12:50 UTC, danjov commented on src/api/appsettings.Development.json
> +    "SECRET_KEY": "YELLOWMONKEY"
REQ: Da es dieselben Settings sind wie in `appsettings.json` müssen diese hier nicht nochmals aufgeführt werden.

2023-04-25 12:50 UTC, danjov commented on tests/BoreholeFileControllerTest.cs
> +        Assert.IsNotNull(boreholeFilesOfBorehole.Value);
REQ: Anstatt einfach zu prüfen, dass die Liste nicht `null` ist, sollte hier stattdessen mindestens der `Count` oder besser die Items in der Liste geprüft werden. Damit das geht müsste man aber nach jedem Upload die Files wieder vom Borehole abhängen und löschen. Das hätte aber den Vorteil, dass diese beiden Vorgänge (_Detach_ und _Delete_) so auch gleich implizit getestet wären.

Dieser Kommentar bezieht sich auf alle weiteren Asserts, die nur auf `null` prüfen oder auf einen simplen Count.

2023-04-25 12:50 UTC, danjov commented on tests/BoreholeFileControllerTest.cs
> +        Assert.AreEqual(boreholeCount, context.Boreholes.Count(), "Tests need to remove boreholes they created.");
Q: Macht diese Prüfung in dieser Klasse Sinn? Erstellen wir überhaupt Boreholes in diesen Tests?

2023-04-25 12:50 UTC, danjov commented on tests/BoreholeFileControllerTest.cs
> +    public async Task DownloadFileShouldReturnDownLoadedFile()
PP: 
```suggestion
    public async Task DownloadFileShouldReturnDownloadedFile()
```

2023-04-25 17:09 UTC, Lehats commented on src/api/Controllers/BoreholeFileController.cs
> +            if (boreholeFile?.File != null)
2te Leerzeile muss bleiben, da ansonsten wegen dem Kommentar eine Warnung erscheint.

2023-04-25 17:12 UTC, Lehats commented on src/api/Controllers/BoreholeFileController.cs
> +                file.BoreholeFiles.Remove(file.BoreholeFiles.First(bf => bf.FileId == boreholeFileId && bf.BoreholeId == boreholeId));
Dann müsste man nochmals einen Request machen damit man weiss, ob das File nun keine Boreholefiles mehr hat.

2023-04-25 17:14 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            if (boreholeFile?.File != null)
Stimmt, danke für den Hinweis.

2023-04-25 17:16 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +                file.BoreholeFiles.Remove(file.BoreholeFiles.First(bf => bf.FileId == boreholeFileId && bf.BoreholeId == boreholeId));
Ich denke das wäre ein fairer Trade-Off und würde den Code verständlicher machen. Können wir aber gerne gemeinsam anschauen.

2023-04-25 17:19 UTC, Lehats commented on src/api/BoreholeFileUploadService.cs
> +        using MinioClient minioClient = initClient.WithEndpoint(endPoint).WithCredentials(accessKey, secretKey).WithSSL(false).Build();
So etwas in der Art oder? 

```private MinioClient CreateMinioClient()
    {
        using var initClient = new MinioClient();
        return initClient.WithEndpoint(endpoint).WithCredentials(accessKey, secretKey).WithSSL(false).Build();
    }

Dann habe ich aber das Problem vom Scope vom "initClient" . Hast du eine Idee?

2023-04-25 17:21 UTC, Lehats commented on src/api/Controllers/BoreholeFileController.cs
> +                file.BoreholeFiles.Remove(file.BoreholeFiles.First(bf => bf.FileId == boreholeFileId && bf.BoreholeId == boreholeId));
Oke. Nein denke von der Leserlichkeit wäre es auf jeden Fall besser. Ich passe das sonst an.

2023-04-25 17:34 UTC, danjov commented on src/api/BoreholeFileUploadService.cs
> +        using MinioClient minioClient = initClient.WithEndpoint(endPoint).WithCredentials(accessKey, secretKey).WithSSL(false).Build();
Ja, in diesem Fall haben wir zwei Optionen:
1. `initClient` in eine Instanzvariable packen und (wieder)verwenden. Das Abräumen von `initClient` überlassen wir dann dem Framework.
2. Wir schalten die FxCop-Rule in diesem Fall ab und verwenden keinen `initClient` mehr, sondern verwenden den Client gemäss der Doku von MinIO: `new MinioClient().WithEndpoint()...`

Lass uns das zusammen anschauen. Ich tendiere zu Option 2.

2023-04-26 11:40 UTC, Lehats commented on src/api/Controllers/BoreholeFileController.cs
> +                context.Files.Remove(file);
So weit ich weiss nicht. Habe auch nochmals nachgeschaut.

2023-04-26 11:42 UTC, danjov requested changes

2023-04-26 11:42 UTC, danjov commented on src/api/Controllers/BoreholeFileController.cs
> +            if (boreholeFile != null)
REQ: Wenn `boreholeFile == null` ist, müssen wir abbrechen und eine entsprechende Meldung zurückgeben, dass das File nicht gefunden werden konnte. Ansonsten haben wir weiter unten das Problem, dass möglicherweise `NullReferenceException`s auftreten können.

2023-04-26 12:03 UTC, danjov approved these changes

2023-04-26 13:21 UTC, danjov approved these changes

2023-04-26 14:55 UTC, merged