Use .Net endpoints in legacy API
geoadmin/suite-bdms pull request #628
Opened 2023-05-01 06:25 UTC by Lehats

Working on #598

2023-05-01 13:03 UTC, danjov requested changes
REQ: Changelog nachführen

2023-05-02 04:45 UTC, Lehats commented on src/api/Controllers/BoreholeFileController.cs
> +        // Do not use .Include(bf => bf.File) here, as it will cause a object cycling.
Gerne, ja. Musste die Json serialize options auch wieder rausnehmen im Program file..

2023-05-02 04:49 UTC, Lehats commented on src/api/Models/BoreholeFileUpdate.cs
> +/// ]]>
Ich dachte das sei nur etwas für Devs. bzw. Personen die den Code sehen und nicht allenfalls die Klasse ausserhalb verwenden. Habe mich auf z.B. den _LocationController_ gestützt. Oder ist es da so gelöst, da die Remarks für den API Konsumenten ersichtlich wären?

2023-05-02 04:56 UTC, Lehats commented on src/api/Models/BoreholeFileUpdate.cs
> +/// ]]>
Habe es aber nun auf ```<remarks>``` geändert.

2023-05-02 06:43 UTC, danjov commented on src/api/Models/BoreholeFileUpdate.cs
> +/// ]]>
Nein nicht ganz. Text in `CDATA` wird auf Zeichen-Basis interpretiert und der Inhalt muss daher nicht _escaped_ werden. Das ist nützlich, wenn man z.B. Beispiel-Code oder -XML im Kommentar unterbringen will, da man nichts _escapen_ muss.

2023-05-02 14:43 UTC, danjov approved these changes

2023-05-02 15:01 UTC, merged