Hydrotest
geoadmin/suite-bdms pull request #629
Opened 2023-05-01 08:42 UTC by MiraGeowerkstatt

#577 
Hydrotest models and controllers

2023-05-01 09:53 UTC, danjov requested changes

2023-05-01 09:53 UTC, danjov commented on src/api/BdmsContextExtensions.cs
> +            .RuleFor(o => o.TestKind, _ => default!);
REQ: `StrictMode(true)` verwenden, falls möglich.

2023-05-01 09:53 UTC, danjov commented on src/api/Migrations/20230428143532_AddHydrotestCodelists.cs
> +                                );
PP/REQ: Das `INSERT`-Statement lässt sich vereinfacht ausdrücken, da die Values kommagetrennt in einem Rutsch hinzugefügt werden können - die Wiederholung von `INSERT INTO` ist in diesem Fall nicht nötig.

Beispiel:
```sql
INSERT INTO bdms.codelist (
    id_cli, geolcode, schema_cli, code_cli,
    text_cli_de, description_cli_de,
    text_cli_fr, description_cli_fr,
    text_cli_it, description_cli_it,
    text_cli_en, description_cli_en,
    order_cli, conf_cli, default_cli, path_cli
) 
VALUES 
    (15203198, '005', 'htestres101', '', 'statischer Formationsdruck', '', '', '', '', '', '', 5, NULL, False, ''),
    (15203199, '006', 'htestres101', '', 'spezifischer Speicherkoeffizient', '', '', '', '', '', '', 6, NULL, False, ''),
    (15203200, '007', 'htestres101', '', 'Lugeon-Wert', '', '', '', '', '', '', 7, NULL, False, ''),
    (15203201, '008', 'htestres101', '', 'relevante Mächtigkeit', '', '', '', '', '', '', 8, NULL, False, ''),
    (15203202, '009', 'htestres101', '', 'keine Angaben', '', '', '', '', '', '', 9, NULL, False, '');

```

2023-05-01 09:53 UTC, danjov commented on tests/HydrotestControllerTest.cs
> +        var hydrotest = hydrotests.Single();
PP: Kann vereinfacht werden zu
```csharp
        IEnumerable<Hydrotest>? hydrotests = await controller.GetAsync(1005438).ConfigureAwait(false);
        var hydrotest = hydrotests?.SingleOrDefault();
        Assert.IsNotNull(hydrotests);
```

2023-05-01 09:53 UTC, danjov commented on tests/HydrotestControllerTest.cs
> +            Id = 1,
PP: Hier sollte ein Kommentar rein, der besagt weshalb das Setzen und Speichern der `Id` in diesem Fall funktioniert und nicht automatisch von der DB generiert wird.

2023-05-01 09:53 UTC, danjov commented on tests/HydrotestResultControllerTest.cs
> +        IEnumerable<HydrotestResult>? hydrotestresults = response;
PP: Lässt sich vereinfachen zu
```csharp
        IEnumerable<HydrotestResult>? hydrotestresults = await controller.GetAsync(12000224).ConfigureAwait(false);
```

2023-05-01 09:53 UTC, danjov commented on tests/HydrotestResultControllerTest.cs
> +        };
Q: Funktioniert das Setzen der `Ids` hier? Die `Id`s für diese Tabelle werden eigentlich von PostgreSQL automatisch generiert.

2023-05-01 11:29 UTC, MiraGeowerkstatt commented on tests/HydrotestResultControllerTest.cs
> +        };
Postgres generiert die primary keys nur, wenn man sie nicht manuell mitgibt.
Wenn sie manuell gesetzt werden, wird auch die sequence nicht hochgezählt.

2023-05-01 11:39 UTC, danjov commented on tests/HydrotestResultControllerTest.cs
> +        };
Danke für die Klarstellung ℹ️

2023-05-01 11:40 UTC, danjov commented on src/api/Migrations/20230428143532_AddHydrotestCodelists.cs
> +                                default_cli, path_cli
PP: Diese Parameter hätte ich auch auf eine Zeile reduziert, so dass man die Values zum jeweiligen Parameter von Auge einfacher zuweisen kann. Kann man aber auch so lassen :)

2023-05-02 07:09 UTC, MiraGeowerkstatt commented on src/api/BdmsContextExtensions.cs
> +            .RuleFor(o => o.TestKind, _ => default!);
Das gehts leider nicht, da dann verlangt wird alle properties nochmal zu setzen, die bereits über die parent Klasse "Observation" gesetzt wurden.

2023-05-02 07:34 UTC, danjov approved these changes

2023-05-02 07:58 UTC, merged