Upload borehole attachments using borehole import feature
geoadmin/suite-bdms pull request #634
Opened 2023-05-04 11:48 UTC by Lehats

Working on #552

2023-05-04 12:07 UTC, danjov requested changes
REQ: Online-Hilfe nachführen.

2023-05-04 12:07 UTC, danjov commented on src/client/public/locale/de/common.json
> +  "dropZoneFileToLarge": "Eine oder mehrere Dateien sind zu groß. Max. 200 MB.",
PP: 
```suggestion
  "dropZoneFileToLarge": "Eine oder mehrere Dateien sind zu gross. Max. 200 MB.",
```

2023-05-04 12:07 UTC, danjov commented on src/client/src/commons/menu/editor/menuEditorSearch.js
> +                  maxFilesToUpload="2"></FileDropzone>
PP: 
```suggestion
                  maxFilesToUpload="2" />
```

2023-05-04 12:07 UTC, danjov commented on tests/BoreholeFileUploadServiceTest.cs
> +        await minioClient.StatObjectAsync(statObjectArgs);
Q: Muss hier noch etwas _asserted_ werden oder genügt das?

2023-05-04 12:07 UTC, danjov commented on CHANGELOG.md
> +- Upload borehole attachments using borehole import feature.
REQ: Dieser Eintrag muss oben in den Bereich `[Unreleased]` verschoben werden.

2023-05-04 12:34 UTC, Lehats commented on src/api/BoreholeFileUploadService.cs
> +            if (transaction != null) await transaction.CommitAsync().ConfigureAwait(false);
Habs schnell versucht. Geht leider nicht.

2023-05-05 07:04 UTC, danjov approved these changes

2023-05-05 07:04 UTC, danjov commented on src/client/docs/import.md
> +1. Schaltfläche _Dateien hier ablegen oder klicken, um sie hochzuladen_ anklicken und die vorbereitete PDF-Datei(en) auswählen.
PP: 
```suggestion
1. Schaltfläche _Dateien hier ablegen oder klicken, um sie hochzuladen_ anklicken und die vorbereitete(n) PDF-Datei(en) auswählen.
```

2023-05-05 07:04 UTC, danjov commented on src/client/docs/import.md
> +Die Anhangsdatei muss den folgenden Anforderungen und dem Format entsprechen, damit sie erfolgreich in die Webapplikation importiert werden kann:
PP: 
```suggestion
Die Anhangsdatei muss den folgenden Anforderungen und Format entsprechen, damit sie erfolgreich in die Webapplikation importiert werden kann:
```

2023-05-05 07:04 UTC, danjov commented on src/client/docs/import.md
> +Für jeden bereitgestellten Header CSV-Datei muss für jede Zeile ein entsprechender Wert angegeben werden, oder leer gelassen werden.
PP: 
```suggestion
Für jeden bereitgestellten Header in der CSV-Datei muss für jede Zeile ein entsprechender Wert angegeben werden, oder leer gelassen werden.
```

2023-05-05 07:05 UTC, merged