Fix s3 access
geoadmin/suite-bdms pull request #643
Opened 2023-05-09 10:16 UTC by Lehats

2023-05-09 11:07 UTC, flenny submitted a review, later dismissed

2023-05-09 11:07 UTC, flenny commented on tests/BoreholeFileControllerTest.cs
> +        var configuration = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string>
PP:
`var configuration = new ConfigurationBuilder().AddJsonFile("appsettings.Development.json").Build();`
Oder geht genau das eben nicht 🤔

2023-05-09 11:26 UTC, Lehats commented on tests/BoreholeFileControllerTest.cs
> +        var configuration = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string>
Ich war so davon überzeugt, dass ich es so versucht habe mit `.AddJsonFile("appsettings.Development.json")`. Habe es nun nochmals versucht und es war tatsächlich erfolgreich. Danke

2023-05-09 11:26 UTC, danjov requested changes

2023-05-09 11:26 UTC, danjov commented on src/api/BoreholeFileUploadService.cs
> +                logger.LogError("Error during get credentials from InstanceProfileAWSCredentials");
REQ: Exception ebenfalls loggen
```csharp
                logger.LogError("Error getting credentials from InstanceProfileAWSCredentials.", ex);
```

2023-05-10 07:08 UTC, danjov approved these changes

2023-05-10 07:38 UTC, merged