Hydrotest client
geoadmin/suite-bdms pull request #646
Opened 2023-05-10 14:39 UTC by MiraGeowerkstatt

2023-05-10 15:08 UTC, danjov requested changes

2023-05-10 15:08 UTC, danjov commented on src/client/src/commons/form/borehole/hydrogeology/hydrotestInput.js
> +  const cannotAddHydrotestResults =
Q: Wäre der umgekehrte Ansatz nicht einfacher verständlich? Also `canAddHydrotestResults` anstatt `cannotAddHydrotestResults`? So muss man im Kopf nicht alles negieren.

2023-05-10 15:08 UTC, danjov commented on src/client/src/commons/form/borehole/hydrogeology/hydrotestResultTable.js
> +              const id = result.id || result.tempId || 0; // blablabla
REQ: Kommentar entfernen

2023-05-11 12:56 UTC, MiraGeowerkstatt commented on CHANGELOG.md
> +- Added functionality to add, edit and delete hydrotests, which belong to the hydrogeology observations of a borehole.
Ja ist mir auch schon aufgefallen, werde das bereinigen.

2023-05-12 15:28 UTC, danjov requested changes

2023-05-15 10:28 UTC, danjov approved these changes

2023-05-15 12:40 UTC, merged