Field measurement UI
geoadmin/suite-bdms pull request #668
Opened 2023-05-16 15:30 UTC by MiraGeowerkstatt

Resolves  #648

2023-05-17 06:22 UTC, danjov requested changes
REQ: Changelog fehlt

2023-05-17 06:22 UTC, danjov commented on src/client/src/commons/form/borehole/hydrogeology/fieldMeasurementInput.js
> +                        ?.filter(d => d.schema === "field101")
Q: Haben wir für die Schemas keine Konstante im Client? Falls nicht, wäre es sinnvoll die entsprechenden Konstanten einzuführen?

2023-05-17 07:14 UTC, MiraGeowerkstatt commented on src/client/src/commons/form/borehole/hydrogeology/fieldMeasurementInput.js
> +                        ?.filter(d => d.schema === "field101")
Gibt noch keine aber wäre sinnvoll!

2023-05-17 12:22 UTC, danjov approved these changes

2023-05-17 14:16 UTC, merged

2023-05-22 09:49 UTC, gysimichael commented
@MiraGeowerkstatt Bei den Werten bräuchte es noch ein Feld mit den Einheiten, sonst alles gut