Streamline from to depths labels
geoadmin/suite-bdms pull request #716
Opened 2023-05-23 15:51 UTC by MiraGeowerkstatt

2023-05-23 15:53 UTC, danjov requested changes
REQ: Warten, bis die PRs https://github.com/geoadmin/suite-bdms/pull/713 und https://github.com/geoadmin/suite-bdms/pull/714 gemerged sind. Danach schauen, ob es gewisse Umbenennungen nicht mehr braucht bzw. Konflikte gelöst werden müssen.

2023-05-23 18:52 UTC, gysimichael commented
> REQ: Warten, bis die PRs #713 und #714 gemerged sind. Danach schauen, ob es gewisse Umbenennungen nicht mehr braucht bzw. Konflikte gelöst werden müssen.

Hier die Syntax, die ich bei mir gebraucht hatte:

DE | EN | FR | IT
-- | -- | -- | --
Von Tiefe [m MD] | From depth [m MD] | De la profondeur [m MD] | Dalla profondità [m MD]
Bis Tiefe [m MD] | To depth [m MD] | À la profondeur [m MD] | Alla profondità [m MD]
Von Tiefe [m ü.M.] | From depth [m.a.s.l.] | De la profondeur [m s.m.] | Dalla profondità [m s.l.m.]
Bis Tiefe [m ü.M.] | To depth [m.a.s.l.] | À la profondeur [m s.m.] | Alla profondità [m s.l.m.]
Abstich [m MD] | Depth [m MD] | Profondeur [m MD] | Profondità [m MD]
Pegel [m ü.M.] | Level [m.a.s.l.] | Niveau [m s.m.] | Livello [m s.l.m.]

Noch zu beachten, bei den Filtern brauchen wir "von" "bis" aber auch "von Teufe" "bis Teufe". Aus meiner sich kann man das gut vereinheitlichen und überall "von" "bis" nutzen

2023-05-24 06:36 UTC, MiraGeowerkstatt commented
> > REQ: Warten, bis die PRs #713 und #714 gemerged sind. Danach schauen, ob es gewisse Umbenennungen nicht mehr braucht bzw. Konflikte gelöst werden müssen.
> 
> Hier die Syntax, die ich bei meinem Pull Request gebraucht hatte:
> 
> DE	EN	FR	IT
> Von Tiefe [m MD]	From depth [m MD]	De la profondeur [m MD]	Dalla profondità [m MD]
> Bis Tiefe [m MD]	To depth [m MD]	À la profondeur [m MD]	Alla profondità [m MD]
> Von Tiefe [m ü.M.]	From depth [m.a.s.l.]	De la profondeur [m s.m.]	Dalla profondità [m s.l.m.]
> Bis Tiefe [m ü.M.]	To depth [m.a.s.l.]	À la profondeur [m s.m.]	Alla profondità [m s.l.m.]
> Abstich [m MD]	Depth [m MD]	Profondeur [m MD]	Profondità [m MD]
> Pegel [m ü.M.]	Level [m.a.s.l.]	Niveau [m s.m.]	Livello [m s.l.m.]
> Noch zu beachten, bei den Filtern brauchen wir "from" "to" aber auch "fromdepth" "todepth". Aus meiner sich kann man das gut vereinheitlichen und überall "from" "to" nutzen

@gysimichael ist es richtig dass es im englischen [m.a.s.l]  und nicht  [m a.s.l.] heisst?

2023-05-24 09:01 UTC, danjov approved these changes

2023-05-24 10:33 UTC, merged