New field  National interest
geoadmin/suite-bdms pull request #808
Opened 2023-06-15 14:11 UTC by tschumpr

Resolves #101

2023-06-16 10:00 UTC, danjov requested changes

2023-06-19 07:11 UTC, danjov commented on src/client/src/commons/form/borehole/segments/restrictionSegment.js
> +        </Form.Group>
Alles klar, danke für die Info. Ich denke wir können es mal so belassen und können dann beim nächsten Mal die Komponente auslagern.

2023-06-19 08:43 UTC, danjov approved these changes

2023-06-19 09:28 UTC, merged

2023-06-19 14:23 UTC, gysimichael commented
Sehr cool, danke auch, dass es gleich im Filter umgesetzt ist, das ist sehr hilfreich!