Add yarp proxy
geoadmin/suite-bdms pull request #885
Opened 2023-12-07 14:16 UTC by Philippluca

Resolves: #872

2023-12-07 15:31 UTC, danjov requested changes
Sobald dieser PR gemerged wird, bitte noch die neue Umgebungsvariable `ReverseProxy__Clusters__pythonApi__Destinations__legacyApi__Address` im [Config-Repo](https://github.com/geoadmin/config-bdms) aufnehmen, und zwar je einmal für [docker](https://github.com/geoadmin/config-bdms/blob/main/.env.template) und [k8s](https://github.com/geoadmin/config-bdms/blob/main/kubernetes-manifests/secrets/boreholes.template.yaml).

2023-12-07 15:31 UTC, danjov commented on src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
> +                logger.LogInformation("Authorized user <{UserName}> for legacy api accessing route <{Route}>", userName.Value, context.Request.Path);
PP: Logging vor den `Invoke` setzen bzw. nach dem Setzen des Headers, so spart man sich das `return`.

2023-12-07 15:31 UTC, danjov commented on src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
> +        Claim? userName;
REQ: Die Variable in die `if`-Anweisung verschieben, da sie ausserhalb nicht benötigt wird.

2023-12-07 15:31 UTC, danjov commented on src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
> +public class LegacyApiAuthenticationMiddleware(ILogger<LegacyApiAuthenticationMiddleware> logger) : IMiddleware
REQ: Klasse sowie Methode mit Code-Kommentaren versehen.

2023-12-07 15:41 UTC, Philippluca commented on src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
> +                logger.LogInformation("Authorized user <{UserName}> for legacy api accessing route <{Route}>", userName.Value, context.Request.Path);
Die Struktur richtet sich nach der [ASP.Net Middleware.](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0). Ich gehe davon aus, dass es sich hier um eine performance relevante Struktur handelt.

2023-12-07 15:44 UTC, danjov commented on src/api/Authentication/LegacyApiAuthenticationMiddleware.cs
> +                logger.LogInformation("Authorized user <{UserName}> for legacy api accessing route <{Route}>", userName.Value, context.Request.Path);
Alles klar, danke für die Info 👍🏻

2023-12-07 15:53 UTC, danjov approved these changes

2023-12-08 09:54 UTC, flenny submitted a review, later dismissed
Nicht vergessen im _config-bdms_ Repo die Docker [Traefik Reverse Proxy](https://github.com/geoadmin/config-bdms/blob/main/docker-compose.yml#L66) Konfiguration anzupassen und die nue ENV zu konfigurieren.

Bei der `api` Kubernetes Konfiguration muss die neue ENV erstellt weden und via Secrets auf den legacy-api Service verweisen. Anschliessend müssen wir im Cluster noch die IngressRouten für /v1 und /v2 anpassen.

2023-12-08 15:06 UTC, flenny approved these changes

2023-12-08 15:09 UTC, danjov approved these changes

2023-12-08 15:19 UTC, merged