Add instrumentation to api
geoadmin/suite-bdms pull request #902
Opened 2023-12-13 08:40 UTC by Lehats

2023-12-13 09:44 UTC, danjov commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationId { get; set; }
Ich finde die Unterscheidung auch schwer, da die Schreibweise auf einen FK hinweist und nicht auf einen Namen. Falls es dieses Feld noch braucht, sollten wir es zu irgendwas anderem umbenennen.

2023-12-13 09:53 UTC, Lehats commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationId { get; set; }
@tschumpr @danjov Ich nehme an das braucht es um die Instrumente im selben Casing oder bei gleicher Tiefe auseinander zu halten. Ähnlich wie die CasingId welche ja auch noch weiterhin gebraucht wird. Aber ich habe das leider vergessen zu fragen am Freitag.

2023-12-13 09:53 UTC, danjov requested changes

2023-12-13 09:53 UTC, danjov commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +    protected override void Up(MigrationBuilder migrationBuilder)
REQ: Datenmigration ausführen, betrifft auch die `Completion`-Tabelle.

2023-12-13 09:53 UTC, danjov commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +                    name: "FK_instrumentation_completion_completion_id",
Q: Ist hier `completion` doppelt?

2023-12-13 09:53 UTC, danjov commented on CHANGELOG.md
> +- Table and controller for instrumentation.
PP: Ich würde diesen Eintrag ausnahmsweise weglassen. Sobald das neue UI für die Instrumente steht, wollen wir eigentlich eher das UI (inkl. API) im Changelog hervorheben anstatt die Tabelle und den Controller → heisst, wir machen einen Changelog Eintrag, sobald das UI fertig ist. Was meinst du dazu?

2023-12-13 09:53 UTC, danjov commented on src/api/Controllers/InstrumentationController.cs
> +    public async Task<ActionResult<IEnumerable<Instrumentation>>> GetAsync([FromQuery] int? completionId = null)
REQ: Einfachheitshalber hier `Task<IEnumerable<Instrumentation>>` als Rückgabetyp verwenden. Das vereinfacht auch die dazugehörigen Unit-Tests.

2023-12-13 10:15 UTC, Lehats commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationId { get; set; }
@tschumpr Diese Id ist aus meiner sicht nicht wirklich technischer Natur. Es ist wohl mehr für den User wichtig. Das heist die _Id_ nützt dem User wohl nicht viel. Oder was denkst du?

@danjov @tschumpr Ich kann Michael gerne fragen ob er einen besseren Vorschlag hat für _InstrumentId_. Dann sollten wir aber analog beim Casing die _CasingId_ anpassen.

2023-12-13 10:17 UTC, Lehats commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +    protected override void Up(MigrationBuilder migrationBuilder)
@danjov @tschumpr Sollten wir die Migrationen nicht erst vornehmen wenn das UI in die neuen Tabellen schreibt?

2023-12-13 10:20 UTC, danjov commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationId { get; set; }
@Lehats Gerne. Vielleicht brauchts das Feld auch nicht (mehr), da wir bei den Instrumente keine _Unterelemente_ wie beim Casing (= _Casing-Elemente_) kennen.

2023-12-13 10:39 UTC, danjov commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +    protected override void Up(MigrationBuilder migrationBuilder)
@Lehats Stimmt, das UI ist in diesem PR ja nicht enthalten. Dann passt das so 👍🏻

2023-12-14 08:23 UTC, Lehats commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +    protected override void Up(MigrationBuilder migrationBuilder)
@tschumpr @danjov Gut, dann machen wir die Migration wenn das UI umgehängt ist. Aber danke euch trotzdem für den Hinweis! Habe zu diesem Zeitpunkt gerade nicht an die Migration gedacht.

2023-12-14 13:34 UTC, Lehats commented on src/api/Migrations/20231213062944_AddInstrumentationTable.cs
> +                    name: "FK_instrumentation_completion_completion_id",
So setzt EF den Namen des FKs zusammen. 

FK_<parent_table>_<child_table>_<child_column_name>

2023-12-15 12:24 UTC, Lehats commented on CHANGELOG.md
> +- Table and controller for instrumentation.
Das passt für mich.

2023-12-15 15:03 UTC, danjov requested changes

2023-12-15 15:03 UTC, danjov commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationName { get; set; }
REQ: Das Property einfach `Name` nennen, der Zusatz `Instrumentation` ist überflüssig, da der Kontext durch die Klasse/Tabelle mit dem Namen `Instrumentation` gegeben ist.

2023-12-15 15:03 UTC, danjov commented on tests/Controllers/InstrumentationControllerTest.cs
> +        var okResult = response.Result as OkObjectResult;
PP: Für das Prüfen von Responses kann einfachheitshalber die [ActionResultAssert](https://github.com/geoadmin/suite-bdms/blob/main/tests/ActionResultAssert.cs)-Klasse verwendet werden. So wird der StatusCode auch gleich mitgeprüft.

2023-12-15 15:03 UTC, danjov commented on tests/Controllers/InstrumentationControllerTest.cs
> +        var okResult = response.Result as OkObjectResult;
PP: Für das Prüfen von Responses kann einfachheitshalber die [ActionResultAssert](https://github.com/geoadmin/suite-bdms/blob/main/tests/ActionResultAssert.cs)-Klasse verwendet werden. So wird der StatusCode auch gleich mitgeprüft.

2023-12-15 15:03 UTC, danjov commented on tests/Controllers/InstrumentationControllerTest.cs
> +        Assert.IsInstanceOfType(response, typeof(OkResult));
PP: Für das Prüfen von Responses kann einfachheitshalber die [ActionResultAssert](https://github.com/geoadmin/suite-bdms/blob/main/tests/ActionResultAssert.cs)-Klasse verwendet werden. So wird der StatusCode auch gleich mitgeprüft.

2023-12-18 07:04 UTC, Lehats commented on src/api/Models/Instrumentation.cs
> +    public string? InstrumentationName { get; set; }
Absolut, stimmt.

2023-12-18 07:43 UTC, danjov requested changes
REQ: CI fixen

2023-12-18 10:36 UTC, merged