Auth parameter über Settings API laden
geoadmin/suite-bdms pull request #943
Opened 2024-01-15 14:25 UTC by Philippluca

Resolves: #938

2024-01-15 16:31 UTC, danjov requested changes

2024-01-15 16:31 UTC, danjov commented on src/api/Controllers/SettingsController.cs
> +    [HttpGet("Auth")]
PP: Routes generell kleinschreiben
```suggestion
    [HttpGet("auth")]
```

2024-01-15 16:31 UTC, danjov commented on src/api/Models/AuthSettings.cs
> +public record AuthSettings(string Authority, string Audience);
REQ: Kurze XML-Beschreibung hinzufügen

2024-01-16 07:15 UTC, flenny commented on src/client/src/BdmsAuthProvider.js
> +      scope: "openid profile email",
PP:
Ich hätte jetzt die _scopes_ auch noch in die Api verschoben, Einfach damit sämtliche OIDC Konfiguration an einem Ort ist.

2024-01-16 07:15 UTC, flenny submitted a review, later dismissed

2024-01-16 14:34 UTC, danjov approved these changes

2024-01-16 14:59 UTC, merged