Completion navigation
geoadmin/suite-bdms pull request #979
Opened 2024-01-24 08:03 UTC by tschumpr

Resolves #906

2024-01-29 13:08 UTC, danjov requested changes
REQ: Changelog-Eintrag für den Komplettumbau der Completion hinzufügen.

2024-01-29 13:08 UTC, danjov commented on src/client/cypress/e2e/editor/instrumentation.cy.js
> +            auth: bearerAuth(token),
Q: Gibt's dafür keine Methode im `testHelper`? Zumindest für die Auth sollte etwas da sein, damit man sich nicht jedesmal wiederholt.

2024-01-29 13:08 UTC, danjov commented on src/client/src/api-lib/actions/stratigraphy.js
> -
REQ: Den entsprechenden Pfad im Legacy-API abräumen bzw. einfach[ diesen Action-Parameter entfernen](https://github.com/geoadmin/suite-bdms/blob/424c705dd5403e9fe43875299e92e9428771eaa1/src/api-legacy/v1/borehole/stratigraphy/layer/producer.py#L18), da der Code noch für das `CREATE` benötigt wird.

2024-01-29 13:40 UTC, danjov approved these changes

2024-01-29 13:40 UTC, danjov commented on CHANGELOG.md
> +- Refactored completion (database, API, UI).
PP: 
```suggestion
- Simplified and restructured the completion section (database, API, UI).
```

2024-01-29 14:01 UTC, danjov approved these changes

2024-01-29 14:05 UTC, Lehats approved these changes

2024-01-29 16:16 UTC, danjov submitted a review, later dismissed

2024-01-30 13:04 UTC, danjov approved these changes

2024-01-30 13:04 UTC, merged